version: "3.9"
services:
  php:
    image: php:8.1-fpm
    volumes:
      - '.:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
