version: "3.9"
services:
  php:
    build: .
    volumes:
      - './src:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  composer:
    image: composer
    volumes:
      - .:/app/
    command: install
